spring:
  datasource:
    url: ${ECHOTRACE_DB_URL:jdbc:postgresql://localhost:5432/echotrace}
    username: ${ECHOTRACE_DB_USERNAME:postgres}
    password: ${ECHOTRACE_DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
